[package]
name = "threadpool-rs"
version = "0.1.0"
edition = "2021"
authors = ["Florian Blöchinger"]
license = "MIT"
repository = "https://github.com/Florian-Bloechinger/threadpool-rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
